/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniguacuRouteImport } from './routes/uniguacu'
import { Route as IndexRouteImport } from './routes/index'

const UniguacuRoute = UniguacuRouteImport.update({
  id: '/uniguacu',
  path: '/uniguacu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/uniguacu': typeof UniguacuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/uniguacu': typeof UniguacuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/uniguacu': typeof UniguacuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/uniguacu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/uniguacu'
  id: '__root__' | '/' | '/uniguacu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UniguacuRoute: typeof UniguacuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uniguacu': {
      id: '/uniguacu'
      path: '/uniguacu'
      fullPath: '/uniguacu'
      preLoaderRoute: typeof UniguacuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UniguacuRoute: UniguacuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
